account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('register_done/<str:username>/', views.register_done, name='register_done'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('', include('django.contrib.auth.urls')),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password', 'password2']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise ValidationError("Passwords do not match.")
        return password2
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email is already in use.")
        return email
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise ValidationError("This email is already in use.")
        return email

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')
    

    

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm
from django.contrib.auth.models import User
from .forms import UserEditForm, ProfileEditForm
from django.contrib.auth import login
from .models import Profile
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, reverse

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_active:
                    # Authentication successful
                    login(request, user)
                    return HttpResponse("Authenticated successfully")
                else:
                    # Inactive user
                    return HttpResponse("Disabled account")
            else:
                # Invalid login
                return HttpResponse("Invalid login")
    else:
        form = LoginForm()

    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html')


User = get_user_model()

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            email = user_form.cleaned_data['email']

            # Check if the email is already in use
            if User.objects.filter(email=email).exists():
                user_form.add_error('email', 'This email is already in use.')
            else:
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])
                new_user.save()
                Profile.objects.create(user=new_user)
                return redirect(reverse('account:login'))
    else:
        user_form = UserRegistrationForm()

    return render(request, 'account/register.html', {'user_form': user_form})

def register_done(request, username):
    new_user = User.objects.get(username=username)
    return render(request, 'account/register_done.html', {'new_user': new_user})

@login_required
def edit_profile(request):
    user = request.user
    

    if request.method == 'POST':
        user_form = UserEditForm(instance=user, data=request.POST)
        profile_form = ProfileEditForm(instance=user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=user)
        profile_form = ProfileEditForm(instance=user.profile)

    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

from django.contrib import messages
from django.shortcuts import render, redirect

def edit_view(request):
    
    messages.success(request, 'Changes saved successfully.')
    messages.error(request, 'Something went wrong while saving changes.')

    return redirect(reverse('account:login'))

templates/base.html
{% load static %}
<html>
<head>
    <title>Bookmarks</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
    <h1>Bookmarks</h1>
    
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>
    
    <div class="header">
        <span class="logo">Logo</span>
        <nav>
            {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if request.path == '/dashboard/' %}class="selected"{% endif %}>
                    <a href="{% url 'account:dashboard' %}">My Dashboard</a>
                </li>
                <li {% if request.path == '/#images/' %}class="selected"{% endif %}>
                    <a href="#">Images</a>
                </li>
                <li {% if request.path == '/#people/' %}class="selected"{% endif %}>
                    <a href="#">People</a>
                </li>
            </ul>
            {% endif %}
        </nav>
        <span class="user">
            {% if user.is_authenticated %}
                Hello, {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}!
                <a href="{% url 'account:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}">Login</a>
            {% endif %}
        </span>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

templates/logged_out.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
    <h2><strong style="font-weight: bold; font-size: 32px;">Logged out</strong></h2>
    <p>You have been successfully logged out. You can <a href="{% url 'account:login' %}">log in again</a>.</p>
{% endblock %}

templates/password_change_done.html
{% extends "base.html" %}
{% block title %}Password changed{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Password changed</strong></h2>
  <p>Your password has been successfully changed.</p>
{% endblock %}

templates/password_change_form.html
{% extends "base.html" %}
{% block title %}Change your password{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Change your password</strong></h2>
  <p>Use the form below to change your password:</p>

  <form method="post">
    {{ form.as_p }}
    <div style="margin-top: 10px;">
        <button type="submit">Change</button>
    </div>
    {% csrf_token %}
  </form>
{% endblock %}

templates/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Password set</strong></h2>
  <p>Your password has been set. You can  <a href="{% url 'account:login' %}">log in now</a>.</p>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Reset your password</strong></h2>
  {% if validlink %}
    <p>Please enter your new password twice:</p>

    <form method="post">
      {{ form.as_p }} 
      {% csrf_token %}
      <div style="margin-top: 10px;">
        <button type="submit">Change my password</button>
    </div>
    </form>
  {% else %}
    <p>The password reset link was invalid, possibly because it has already been used.Please request a new password reset.</p>
  {% endif %}
{% endblock %}

templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Reset your password</strong></h2>
  <p>We've emailed you instructions for setting your password.</p>

  <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
{% endblock %}

templates/password_reset_email.html
Someone asked for a password reset for the email address: {{ email }}.
Follow the link below to reset your password:

{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.get_username }}

templates/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
  <h2><strong style="font-weight: bold; font-size: 32px;">Forgotten your password?</strong></h2>
  <p>Enter your e-mail address to obtain a new password:</p>

  <form method="post">
    {{ form.as_p }}
    <div style="margin-top: 10px;">
        <button type="submit">Send e-mail</button>
    </div>
    {% csrf_token %}
  </form>
{% endblock %}